version: "2"
services:
  jupyterlab-opencv:
    container_name: jupyterlab-opencv
    build:
      context: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "C:/Users/user01/work/opencv/:/home/jovyan/work/" # ← notebookをホストと共有したいためディレクトリをマウント
    environment:
      NB_UID: 500 # ← 作業するユーザーのUID 私の環境では500だったので500を指定
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --NotebookApp.token=''
    